# Generated by Django 3.2.12 on 2022-02-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
